title: HarmonyChain Docs
description: Decentralized music platform - architecture, components, and user guide
remote_theme: just-the-docs/just-the-docs
url: https://<your-org>.github.io/HarmonyChain
logo: /assets/logo.svg
aux_links:
  GitHub Repository: https://github.com/<your-org>/HarmonyChain
color_scheme: light
search_enabled: true
nav_enabled: true
navigation:
  - title: Overview
    url: /
  - title: Architecture
    url: /architecture
  - title: Components
    url: /components
  - title: Developer Guide
    url: /developer-guide
  - title: User Guide
    url: /user-guide
  - title: Roadmap
    url: /roadmap


